### ISSUE TITLE
how to write cmakelist.txt file,

### ISSUE THREAD

**Issue by 13567436138** [htw0056/redis-3.0-annotated-cmake-in-clion#2]
I have a source of bash,I need run it in clion with cywin.I don't know how to write cmakelist.txt file.
the cmakelist.txt file generate by clion has error

**Comment by htw0056** [comment]
I'm sorry, this issues is not related to this project, I'll close this issues.
BTW, I think you need to learn [Make](https://www.gnu.org/software/make/) and [CMake](https://cmake.org/). Then you can write cmakelist.txt based on the Makefile.
If you can read Chinese, the answer to this question may help. #1
