### ISSUE TITLE
Redis6.0 cmake file

### ISSUE THREAD

**Issue by LHRchina** [htw0056/redis-3.0-annotated-cmake-in-clion#3]

**Comment by htw0056** [comment]
最新版CLion已支持Makefile，redis6.0源码无需再适配CMake。
克隆Redis仓库后，使用最新版CLion直接导入代码即可运行。

NOTE: [Makefile projects in CLion: now public!](https://blog.jetbrains.com/clion/2020/06/makefile-projects-in-clion/)
